# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none 

pool:
  name: agentpool


stages:
  - stage: terraformInstall
    displayName: terraform install 
    jobs: 
    - job: terraform_install_init_validate_plan
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
    
      - script: |
          tflint --recursive --format junit > tflint-report.xml
          exit /b 0
        displayName: Terraform linting
        workingDirectory: '$(System.DefaultWorkingDirectory)\environments\dev'
      - task: InfracostSetup@2
        inputs:
          apiKey: 'ico-FnnkwnKY7yAIwhZUPbiN1WdDjymPmHed'
          version: '0.10.x'

      - script: |
          infracost breakdown --path .
          exit /b 0
        displayName: Terraform infracost
        workingDirectory: '$(System.DefaultWorkingDirectory)\environments\dev'      

      - task: TerraformTask@5
        displayName: init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)\environments\dev'
          backendServiceArm: 'practice_23-12-25'
          backendAzureRmStorageAccountName: 'todoinfrabestate'
          backendAzureRmContainerName: 'terraformstate'
          backendAzureRmKey: 'terraform.tfstate'

      - task: TerraformTask@5
        displayName: validate      
        inputs:
          provider: 'azurerm'
          command: 'validate'
          workingDirectory: '$(System.DefaultWorkingDirectory)\environments\dev'

      - task: TerraformTask@5
        displayName: plan      
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(System.DefaultWorkingDirectory)\environments\dev'
          environmentServiceNameAzureRM: 'practice_23-12-25'
      

      - task: TerraformTask@5
        displayName: apply
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(System.DefaultWorkingDirectory)\environments\dev'
          environmentServiceNameAzureRM: 'practice_23-12-25'

  